### ISSUE TITLE
hello 这份源码可以用么

### ISSUE THREAD

**Issue by lhjandroid** [huoji120/PUBG-Cheat-By-huoji-and-Lee#2]

**Comment by huoji120** [comment]
hello , 请问我是一个残疾人我只会ctrl+c和ctrl+v的写代码,现在我看到了你的源码,现在我想问问能不能用,能用的我就加个壳拿去卖了,请问可以吗.傻吊小学生你妈全家死了废物只想赚钱的废物,赚你妈的钱你妈就是这幅德行被操得要你去粘贴代码赚钱.
